### ISSUE TITLE
Support OpenShift IPv6 DualStack 

### ISSUE THREAD

**Issue by rbo** [RedHat-EMEA-SSA-Team/hetzner-ocp4#182]
With OpenShift 4.8 Red Hat added support for OpenShift IPv6 Single and DualStack I would like to set up DualStack on hetzner. (Requires OVNKubernetes)

Hetzner assign a /64 to the hetzner server, Idea is to use a smaller subnet /80 for OpenShift Nodes:

```
2a01:04f8:0061:20e1:0000:0000:0000:0000
                   │    │    │    │
                   │    │    │    └── /112 Subnet
                   │    │    │
                   │    │    └── /96 Subnet
                   │    │
                   │    └── /80 Subnet  
                   │
                   └── /64 Subnet            
```
Source: https://docs.hetzner.com/robot/dedicated-server/ip/additional-ip-adresses/#subnets

Findout subnet with ansible:
```bash
$ ansible -m setup -a 'filter=ansible_all_ipv6_addresses' localhost
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv6_addresses": [
            "fe80::fc54:ff:fea8:340c",
            "fe80::fc54:ff:fea8:340a",
            "fe80::fc54:ff:fea8:340b",
            "2a01:4f8:10a:1fe0::2",
            "fe80::3ad5:47ff:fe02:d663",
            "fe80::fc54:ff:fea8:340d"
        ]
    },
    "changed": false
}
$

```

Hetzner assign `<SUBNET>::2` to the node.

## ToDo's
- [x] Check Hetzner firewall with ipv6 the openshift nodes are exposed to the internet.
- [X] Add `ip_families` config switch, default should be `false` : `ip_families="['IPv4','IPv6']"`
- [x] Test Public DNS
  - [x] CloudFlare
  - [x] GCP
  - [x] AWS
  - [x] Hetzner
  - [x] Azure
 - [x] Test Compact cluster
 - [x] Test SingleNode

**Comment by rbo** [comment]
Looks like ```{{ hostvars['localhost']['ansible_default_ipv6']['address'] }}``` is better then `ansible_all_ipv6_addresses`
```bash
 ansible -m setup localhost | grep -A10 ansible_default_ipv6
        "ansible_default_ipv6": {
            "address": "2a01:4f8:10a:1fe0::2",
            "gateway": "fe80::1",
            "interface": "enp4s0",
            "macaddress": "38:d5:47:02:d6:63",
            "mtu": 1500,
            "prefix": "64",
            "scope": "global",
            "type": "ether"
        },
        "ansible_device_links": {
```

**Comment by rbo** [comment]
I miss some dhcp settings ad RHCOS dhcp client:
```
ipv6.dhcp-duid=ll
ipv6.dhcp-iaid=mac 
```
https://coreos.slack.com/archives/CQQ7P8UTT/p1626797001053700

It looks like assisted installer add an ignition configuration for that: 
https://github.com/openshift/assisted-service/blob/061bdace8ec78616bb6715b39a5f087223ade971/internal/ignition/ignition.go#L195-L202
https://github.com/openshift/assisted-service/blob/061bdace8ec78616bb6715b39a5f087223ade971/internal/ignition/ignition.go#L1291
https://github.com/openshift/assisted-service/blob/061bdace8ec78616bb6715b39a5f087223ade971/internal/ignition/ignition.go#L1291

**Comment by rbo** [comment]
Official IPv6 is only supported on BareMetal IPI: https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html#ocp-4-8-dual-stack-support-bare-metal-ovn-kubernetes-network-provider

**Comment by rbo** [comment]
```
$ virsh net-dhcp-leases ipv6                                                                                                           host01: Wed Jul 21 14:29:55 2021

 Expiry Time           MAC address         Protocol   IP address                      Hostname    Client ID or DUID
---------------------------------------------------------------------------------------------------------------------------------
 2021-07-21 15:11:38   52:54:00:a8:80:02   ipv6       2a01:4f8:10a:1fe0:80::2/80      bootstrap   00:03:00:01:52:54:00:a8:80:02
 2021-07-21 15:14:28   52:54:00:a8:80:02   ipv4       192.168.128.2/24                bootstrap   01:52:54:00:a8:80:02
 2021-07-21 15:16:18   52:54:00:a8:80:0a   ipv6       2a01:4f8:10a:1fe0:80::1000/80   master-0    00:03:00:01:52:54:00:a8:80:0a
 2021-07-21 15:17:34   52:54:00:a8:80:0a   ipv4       192.168.128.10/24               master-0    01:52:54:00:a8:80:0a
 2021-07-21 15:16:05   52:54:00:a8:80:0b   ipv6       2a01:4f8:10a:1fe0:80::1001/80   master-1    00:03:00:01:52:54:00:a8:80:0b
 2021-07-21 15:17:34   52:54:00:a8:80:0b   ipv4       192.168.128.11/24               master-1    01:52:54:00:a8:80:0b
 2021-07-21 15:16:37   52:54:00:a8:80:0c   ipv6       2a01:4f8:10a:1fe0:80::1002/80   master-2    00:03:00:01:52:54:00:a8:80:0c
 2021-07-21 15:17:34   52:54:00:a8:80:0c   ipv4       192.168.128.12/24               master-2    01:52:54:00:a8:80:0c
 2021-07-21 15:25:23   52:54:00:a8:80:0d   ipv6       2a01:4f8:10a:1fe0:80::1003/80   compute-0   00:03:00:01:52:54:00:a8:80:0d
 2021-07-21 15:26:54   52:54:00:a8:80:0d   ipv4       192.168.128.13/24               compute-0   01:52:54:00:a8:80:0d

$  oc describe node/master-0 | grep -A5 Addresses
Addresses:
  InternalIP:  192.168.128.10
  InternalIP:  2a01:4f8:10a:1fe0:80::1000
  Hostname:    master-0
Capacity:
  cpu:                4
```

**Comment by rbo** [comment]
### Check Hetzner firewall with ipv6 the openshift nodes are exposed to the internet.
IPv6 firewalling is available as a hetzner service. This has to be done on the Linux host system.

**Comment by rbo** [comment]
Added some notes about IPv6 & hetzner.

**Comment by rbo** [comment]
Merged into devel will be merge with #183 into master
