### ISSUE TITLE
Use Quay.io as source for image registry mirror

### ISSUE THREAD

**Issue by tahonen** [RedHat-EMEA-SSA-Team/hetzner-ocp4#66]
Disconnected installation is using docker registry image from docker.io. That may be blocked and cannot be use in some cases. Quay.io is usually whitelisted so change registry image to point to quay.io/redhat-emea-ssa-team/registry image repo.

**Comment by rbo** [comment]
**ToDos**

- [ ] Create skopeo-ubi image https://github.com/RedHat-EMEA-SSA-Team/skopeo-ubi
- [ ] Create service account for https://quay.io/repository/redhat-emea-ssa-team/registry 
- [ ] Setup regular sync via CronJob at [openshift online](https://employee.openshift.com/)

**Comment by rbo** [comment]
Will be merged with PR #75
